export type { ApiDepartment, ApiDepartmentStatistic, ApiDepartmentTrainingGroup, ApiDepartmentTrainingSession, DepartmentAPI } from "./api/department.types.js";
export type { JsonLdContext, JsonLdResource } from "./api/json-ld.types.js";
export type { Location, LocationSummary } from "./api/location.types.js";
export type { Department } from "./departments/department.types.js";
export type { DepartmentLocation, DepartmentLocationAmenity } from "./departments/department-location.types.js";
export type { DepartmentStat } from "./departments/department-stat.types.js";
export type { DepartmentTrainer, DepartmentTrainerContactPerson, TrainerLicense } from "./departments/department-trainer.types.js";
export type { DepartmentTrainingGroup } from "./departments/department-training-group.types.js";
export type { DepartmentTrainingSession } from "./departments/department-training-session.types.js";
export type { MediaItem } from "./media-items/media-item.types.js";
